version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: my_tomcat
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db